import gradio as gr
from generate_image import generate_with_hf, generate_with_pollinations
import os

def generate(prompt, method, token):
    if not prompt:
        return None, "Please enter a prompt."
    
    try:
        if method == "Pollinations.ai (Free, No Key)":
            image = generate_with_pollinations(prompt)
            if image:
                return image, "Success!"
            else:
                return None, "Failed to generate image with Pollinations."
                
        elif method == "Hugging Face (Requires Key)":
            if not token:
                # Try validation from env var if not provided in UI
                token = os.environ.get("HF_TOKEN")
            
            if not token:
                return None, "Error: Hugging Face Token is required for this method."
                
            image = generate_with_hf(prompt, token)
            if image:
                return image, "Success!"
            else:
                return None, "Failed to generate image with Hugging Face. Check your token."
    except Exception as e:
        return None, f"An error occurred: {str(e)}"

    return None, "Unknown error."

with gr.Blocks(title="Free AI Image Generator") as demo:
    gr.Markdown("# ✨ Free AI Image Generator")
    gr.Markdown("Create images using free AI APIs. generated by Antigravity.")
    
    with gr.Row():
        with gr.Column():
            prompt_input = gr.Textbox(label="Image Prompt", placeholder="A futuristic city with flying cars, cyberpunk style...")
            
            method_input = gr.Radio(
                ["Pollinations.ai (Free, No Key)", "Hugging Face (Requires Key)"],
                label="Generation Method",
                value="Pollinations.ai (Free, No Key)"
            )
            
            token_input = gr.Textbox(
                label="Hugging Face Token (Optional for Pollinations)", 
                placeholder="hf_...", 
                type="password",
                visible=False
            )
            
            # Show token input only when HF is selected
            def update_visibility(method):
                return gr.update(visible=(method == "Hugging Face (Requires Key)"))
            
            method_input.change(fn=update_visibility, inputs=method_input, outputs=token_input)
            
            btn = gr.Button("Generate Image", variant="primary")
            
        with gr.Column():
            image_output = gr.Image(label="Generated Image")
            status_output = gr.Textbox(label="Status", interactive=False)

    btn.click(fn=generate, inputs=[prompt_input, method_input, token_input], outputs=[image_output, status_output])

if __name__ == "__main__":
    demo.launch()
